- name: "Install Mamba and Python Packages"
  hosts: localhost
  connection: local
  vars:
    poetry_url: https://install.python-poetry.org
    # NEED TO DO POETRY!
  tasks:
    - name: "Is Already Installed"
      ansible.builtin.script:
        cmd: /home/miniconda/bin/mamba
      ignore_errors: true
      register: cmd_output
    - name: "Install Mamba"
      ansible.builtin.script:
        cmd: /home/miniconda/bin/conda install -c conda-forge -y mamba
      when: cmd_output.rc != 0
    - name: "Install Python Packages"
      ansible.builtin.script:
        cmd: |
          /home/miniconda/bin/mamba install -y \
            altair \
            black \
            flake8 \
            jupyter \
            matplotlib \
            numpy \
            pandas \
            pydocstyle \
            pylint \
            pytest \
            requests
      when: cmd_output.rc != 0

