---
# Updated: 2023-11-19

# REF: https://github.com/GoogleCloudPlatform/terraformer/tree/master
- name: "[Terraformer] Check if Terraformer exists"
  ansible.builtin.shell:
    cmd: ". {{ HOME }}/.bashrc && terraformer -v"
  ignore_errors: true
  register: terraformer_result

# We clean up on the last line since sometimes terraformer-all-linux-amd64 stays there for some reason.
- name: "[Terraformer] Install Terraformer"
  become: true
  ansible.builtin.shell:
    cmd: |
      rm -rf /tmp/terraformer* \
      && curl -L "{{ TERRAFORMER_PKG_URL }} | grep tag_name | cut -d '"' -f 4)/terraformer-all-linux-amd64" -o /tmp/terraformer \
      && chmod +x /tmp/terraformer \
      && mv /tmp/terraformer /usr/local/bin/terraformer \
      && rm -f /tmp/terraformer
  when: terraformer_result.rc != 0
