---
- name: Install JSalv Desktop Applications
  hosts: localhost
  connection: local
  become: true
  tasks:

    - name: "{{ item }}"
      ansible.builtin.include_tasks: "./playbooks/{{ item }}.yaml"
      loop:
        - create_dirs
        - configure_ssh
        - add_to_path
        # - install_omz
        # - install_miniforge
        # - install_aws_cli
        # - install_pip_packages
        # - install_terraform
        # - install_helm
        - install_golang
        - install_k8s
