---
# Updated: 2024-04-11

- name: "[OMZ] Check if OMZ is installed"
  ansible.builtin.shell:
    cmd: ". {{ HOME }}/.bashrc && omz version"
  ignore_errors: true
  register: omz_result

- name: Install Oh My Zsh # noqa: latest
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: ~/.oh-my-zsh
    depth: 1
  when: omz_result.rc != 0