---
# Updated: 2023-11-19

- name: "[OMZ] Check if OMZ is installed"
  ansible.builtin.shell:
    cmd: ". {{ HOME }}/.bashrc && omz version"
  ignore_errors: true
  register: omz_result

- name: "Install OMZ Block"
  ansible.builtin.shell:
    cmd: |
      curl -Ls -O https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh \
      && ./install.sh \
      && rm install.sh
  when: omz_result.rc != 0
