---
# Updated: 2023-02-27

# Note: We use a gross hack here.
# We can't source bashrc for subsequent tasks, so we need
# to call `. {{ HOME }}/.bashrc &&` for anything that needs to use `go`.
- name: "[Go] Check Go Install"
  ansible.builtin.shell:
    cmd: . {{ HOME }}/.bashrc && go version
  ignore_errors: true
  register: go_result

- name: "[GO] Install Golang"
  # become: true
  ansible.builtin.shell:
    cmd: |
      rm -rf {{ HOME }}/tmp_go \
      && mkdir -p {{ HOME }}/tmp_go \
      && curl -Lo {{ HOME }}/tmp_go/golang.tar.gz {{GOLANG_LATEST_URL}} \
      && tar -C {{ HOME }} -xzf {{ HOME }}/tmp_go/golang.tar.gz \
      && rm -rf {{ HOME }}/tmp_go \
      && echo "export PATH=\$PATH:\"{{ HOME }}/go/bin\"" >> {{ HOME }}/.bashrc
  when: go_result.rc != 0
